### PR TITLE
fix Warning: count(): Parameter must be an array or an object that im…

### PR DESCRIPTION
**Pull request by remicollet**
…plements Countable.. (PHP 7.2)

### CODE REVIEW

**Comment by yunosh** [comment]
Why would it not be an array? Sounds like a wrong usage problem instead?

**Comment by remicollet** [comment]
@yunosh this fix failure from the test suite, NULL seems a current case.

**Comment by Chi-teck** [comment]
Can we just turn into array default value of rowdata parameter?
```
- function _updateRowsCols($rowdata = null)
+ function _updateRowsCols($rowdata = array())
```

**Comment by pounard** [comment]
I don't care about the solution, but this needs to be fixed now that PHP 7.2 is released. By the way, it could be anything that is traversable, right ?

**Comment by timhilliard** [comment]
I like is_array over default of array() as it checks the value being sent to the function as well as the default. I think either way this is fine and given this passes tests I'm hoping it can be merged soon.

**Comment by yunosh** [comment]
Version 1.3.1 has been released.

**Comment by Chi-teck** [comment]
@yunosh could you please update the composer package
https://packagist.org/packages/pear/console_table

**Comment by yunosh** [comment]
Done

**Pull request merged**
